import { Inter } from 'next/font/google';
import './globals.css';

import Header from '@/components/Header';
import SessionWrapper from '@/components/SessionWrapper';
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Instagram Clone',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <SessionWrapper>
      <html lang='en'>
        <body className={inter.className}>
          <Header />
          <Toaster />
          {children}
        </body>
      </html>
    </SessionWrapper>
  );
}
